/**
 * Bengali interface text, keyed by the English. Plain words a farmer uses; crop and place names stay as written.
 * Missing keys fall back to English (see `translate`).
 */
export const BN: Record<string, string> = {
  // Shell
  Questions: 'প্রশ্ন',
  Advisor: 'পরামর্শক',
  'AI advisor': 'এআই পরামর্শক',
  Write: 'লিখুন',
  'Sign in': 'সাইন ইন',
  'Get started': 'শুরু করুন',
  Search: 'খুঁজুন',
  'Search stories': 'লেখা খুঁজুন',
  Main: 'প্রধান',
  'Your stories': 'আপনার লেখা',
  Library: 'লাইব্রেরি',
  Settings: 'সেটিংস',
  Categories: 'বিভাগ',
  'Sign out': 'সাইন আউট',
  Account: 'অ্যাকাউন্ট',
  'Your account': 'আপনার অ্যাকাউন্ট',
  Loading: 'লোড হচ্ছে',
  'Light theme': 'হালকা রং',
  'Dark theme': 'গাঢ় রং',

  // Home and feed
  'Farming knowledge from people who grow it.': 'যাঁরা ফসল ফলান, তাঁদের কাছ থেকে চাষের জ্ঞান।',
  'Stories from farmers and agronomists across Bangladesh, answers to the questions you have this season, and an advisor that shows you where its advice came from.':
    'সারা বাংলাদেশের কৃষক ও কৃষিবিদদের লেখা, এই মৌসুমে আপনার প্রশ্নের উত্তর, আর এমন এক পরামর্শক যে দেখিয়ে দেয় তার পরামর্শ কোথা থেকে এসেছে।',
  'Join AgroTrends': 'অ্যাগ্রোট্রেন্ডসে যোগ দিন',
  'Ask a question': 'প্রশ্ন করুন',
  Stories: 'লেখা',
  Feeds: 'ফিড',
  'For you': 'আপনার জন্য',
  Latest: 'সর্বশেষ',
  Trending: 'জনপ্রিয়',
  'Try again': 'আবার চেষ্টা করুন',
  'Clear filters': 'ফিল্টার মুছুন',
  'Read the latest stories': 'সর্বশেষ লেখা পড়ুন',
  'Write a story': 'লেখা লিখুন',
  'No stories match these filters': 'এই ফিল্টারে কোনো লেখা নেই',
  'Remove a filter, or ask the community about it.': 'একটি ফিল্টার সরান, অথবা অন্যদের কাছে জানতে চান।',
  'Your feed is waiting for you': 'আপনার ফিড আপনার অপেক্ষায়',
  'Follow authors and topics, and their new stories show up here.': 'লেখক ও বিষয় অনুসরণ করুন, তাঁদের নতুন লেখা এখানে আসবে।',
  'No stories yet': 'এখনো কোনো লেখা নেই',
  'Be the first to share what is working in your field.': 'আপনার মাঠে যা কাজ করছে, প্রথম আপনিই লিখুন।',
  "You're all caught up.": 'সব পড়া হয়ে গেছে।',
  "Couldn't load more stories.": 'আর লেখা আনা গেল না।',
  'Loading stories': 'লেখা লোড হচ্ছে',
  'Show more stories': 'আরও লেখা দেখুন',
  '{n} min read': '{n} মিনিটে পড়া',

  // Seasons and farming
  Rabi: 'রবি',
  'Kharif-1': 'খরিফ-১',
  'Kharif-2': 'খরিফ-২',
  'Year-round': 'সারা বছর',
  now: 'এখন',
  'Mid-Oct to mid-Mar': 'মধ্য অক্টোবর থেকে মধ্য মার্চ',
  'Mid-Mar to mid-Jul': 'মধ্য মার্চ থেকে মধ্য জুলাই',
  'Mid-Jul to mid-Oct': 'মধ্য জুলাই থেকে মধ্য অক্টোবর',
  'Crop seasons': 'ফসলের মৌসুম',
  '{season} season stories': '{season} মৌসুমের লেখা',
  Clay: 'এঁটেল',
  Loam: 'দোআঁশ',
  'Clay loam': 'এঁটেল দোআঁশ',
  Sandy: 'বেলে',
  'Sandy loam': 'বেলে দোআঁশ',
  Silt: 'পলি',
  Peat: 'পিট',
  Saline: 'লবণাক্ত',
  Acidic: 'অম্লীয়',
  Crop: 'ফসল',
  Season: 'মৌসুম',
  Region: 'এলাকা',
  Soil: 'মাটি',
  'Any soil': 'যেকোনো মাটি',
  'Farming details': 'চাষের তথ্য',
  'Farming context': 'চাষের প্রসঙ্গ',
  'Clear all': 'সব মুছুন',
  'Filter by crop, region or soil': 'ফসল, এলাকা বা মাটি দিয়ে বাছুন',
  'Show stories': 'লেখা দেখুন',

  // Story
  'Edit story': 'লেখা সম্পাদনা',
  'Draft — only you can see this': 'খসড়া — শুধু আপনি দেখতে পাচ্ছেন',
  'Loading story': 'লেখা লোড হচ্ছে',
  Tags: 'বিষয়',
  'Related stories': 'সম্পর্কিত লেখা',
  'Written by': 'লিখেছেন',
  'About the author': 'লেখক সম্পর্কে',
  'Edit profile': 'প্রোফাইল সম্পাদনা',
  Follow: 'অনুসরণ করুন',
  Following: 'অনুসরণ করছেন',
  'Clap for this story': 'এই লেখায় হাততালি দিন',
  clap: 'হাততালি',
  claps: 'হাততালি',
  'Sign in to clap': 'হাততালি দিতে সাইন ইন করুন',
  'Sign in to save': 'সংরক্ষণ করতে সাইন ইন করুন',
  'You gave this story 50 claps': 'আপনি এই লেখায় ৫০টি হাততালি দিয়েছেন',
  'Loading author': 'লেখক লোড হচ্ছে',
  Specialities: 'বিশেষজ্ঞতা',

  // Responses and answers
  Responses: 'মন্তব্য',
  Response: 'মন্তব্য',
  'Your response': 'আপনার মন্তব্য',
  Respond: 'মন্তব্য করুন',
  'Response posted': 'মন্তব্য দেওয়া হয়েছে',
  'Sign in to respond': 'মন্তব্য করতে সাইন ইন করুন',
  'Edit your response': 'আপনার মন্তব্য সম্পাদনা',
  'Delete this response?': 'এই মন্তব্য মুছবেন?',
  "No responses yet. Share what worked, or what didn't, on your farm.": 'এখনো কোনো মন্তব্য নেই। আপনার জমিতে কী কাজ করেছে বা করেনি, জানান।',
  'What are your thoughts?': 'আপনার কী মনে হয়?',
  Answers: 'উত্তর',
  Answer: 'উত্তর',
  'Your answer': 'আপনার উত্তর',
  'Post answer': 'উত্তর দিন',
  'Answer posted': 'উত্তর দেওয়া হয়েছে',
  'Sign in to answer': 'উত্তর দিতে সাইন ইন করুন',
  'Edit your answer': 'আপনার উত্তর সম্পাদনা',
  'Delete this answer?': 'এই উত্তর মুছবেন?',
  'No answers yet. If you have grown this, your answer helps.': 'এখনো কোনো উত্তর নেই। আপনি এটা চাষ করে থাকলে আপনার উত্তর কাজে লাগবে।',
  'What has worked for you?': 'আপনার ক্ষেত্রে কী কাজ করেছে?',
  '{item} by {name}': '{name}-এর {item}',
  Reply: 'জবাব দিন',
  Edit: 'সম্পাদনা',
  Delete: 'মুছুন',
  Cancel: 'বাতিল',
  'Keep it': 'রেখে দিন',
  Save: 'সংরক্ষণ',

  // Search and topics
  'Search AgroTrends': 'অ্যাগ্রোট্রেন্ডসে খুঁজুন',
  'Search – AgroTrends': 'খুঁজুন – অ্যাগ্রোট্রেন্ডস',
  'Look for a crop, a pest, a practice or a place.': 'কোনো ফসল, পোকা, চাষের পদ্ধতি বা জায়গা খুঁজুন।',
  'Or browse a topic': 'অথবা কোনো বিষয় দেখুন',
  'Search stories, crops, pests': 'লেখা, ফসল, পোকা খুঁজুন',
  'Matching topics': 'মিলে যাওয়া বিষয়',
  'Try fewer or different words, or ask the community.': 'কম বা অন্য শব্দে খুঁজুন, অথবা অন্যদের জিজ্ঞেস করুন।',
  Topics: 'বিষয়',
  Topic: 'বিষয়',
  'Topics to follow': 'অনুসরণ করার বিষয়',
  'See all topics': 'সব বিষয় দেখুন',
  'Topics – AgroTrends': 'বিষয় – অ্যাগ্রোট্রেন্ডস',
  'Crops, pests, soils and practices people write about. Follow a topic to see its stories in For you.':
    'ফসল, পোকা, মাটি আর চাষের পদ্ধতি নিয়ে মানুষ যা লেখেন। কোনো বিষয় অনুসরণ করলে তার লেখা "আপনার জন্য"-তে আসবে।',
  'You follow': 'আপনি অনুসরণ করছেন',
  'Topics you follow': 'আপনার অনুসরণ করা বিষয়',
  'Find a topic': 'বিষয় খুঁজুন',
  'Loading topics': 'বিষয় লোড হচ্ছে',
  "Couldn't load topics. Try again in a moment.": 'বিষয়গুলো আনা গেল না। একটু পরে আবার চেষ্টা করুন।',
  'No stories on this topic yet': 'এই বিষয়ে এখনো কোনো লেখা নেই',
  'Follow it to see new ones in For you, or write the first.': 'অনুসরণ করুন, নতুন লেখা "আপনার জন্য"-তে আসবে। অথবা প্রথম লেখাটি আপনিই লিখুন।',

  // Questions
  'Questions – AgroTrends': 'প্রশ্ন – অ্যাগ্রোট্রেন্ডস',
  'Ask the community about your crop, your soil, your season.': 'আপনার ফসল, মাটি আর মৌসুম নিয়ে সবাইকে জিজ্ঞেস করুন।',
  'Ask the first one. Farmers and agronomists answer here.': 'প্রথম প্রশ্নটি আপনিই করুন। কৃষক ও কৃষিবিদরা এখানে উত্তর দেন।',
  'Loading questions': 'প্রশ্ন লোড হচ্ছে',
  'Show more questions': 'আরও প্রশ্ন দেখুন',
  'No questions yet': 'এখনো কোনো প্রশ্ন নেই',
  'No questions match these filters': 'এই ফিল্টারে কোনো প্রশ্ন নেই',
  'Edit question – AgroTrends': 'প্রশ্ন সম্পাদনা – অ্যাগ্রোট্রেন্ডস',
  'Ask a question – AgroTrends': 'প্রশ্ন করুন – অ্যাগ্রোট্রেন্ডস',
  'Edit your question': 'আপনার প্রশ্ন সম্পাদনা',
  'Save question': 'প্রশ্ন সংরক্ষণ',
  'Post question': 'প্রশ্ন পোস্ট করুন',
  'Write your question in a line.': 'এক লাইনে আপনার প্রশ্ন লিখুন।',
  'Add what you have seen and tried.': 'কী দেখেছেন আর কী চেষ্টা করেছেন, লিখুন।',
  'AI-generated draft, not reviewed': 'এআই-এর তৈরি খসড়া, যাচাই করা হয়নি',
  Question: 'প্রশ্ন',
  'Asked {date}': '{date} জিজ্ঞেস করেছেন',
  'Delete this question and its answers?': 'এই প্রশ্ন ও এর উত্তরগুলো মুছবেন?',
  'Loading question': 'প্রশ্ন লোড হচ্ছে',
  'Say what you grow, where, and what you have already tried. Specific questions get useful answers.':
    'কী চাষ করছেন, কোথায়, আর এরই মধ্যে কী চেষ্টা করেছেন — লিখুন। নির্দিষ্ট প্রশ্নে কাজের উত্তর মেলে।',
  'Your question': 'আপনার প্রশ্ন',
  'Why are my boro seedlings turning yellow?': 'আমার বোরো চারা হলুদ হয়ে যাচ্ছে কেন?',
  Details: 'বিস্তারিত',
  'Variety, age of the crop, weather, what you applied and when…': 'জাত, ফসলের বয়স, আবহাওয়া, কী দিয়েছেন আর কখন…',
  'See an AI draft answer': 'এআই-এর খসড়া উত্তর দেখুন',
  'AI draft answer': 'এআই-এর খসড়া উত্তর',
  'Not posted. If you know better, answer in your own words above.': 'এটি পোস্ট হয়নি। আপনি ভালো জানলে ওপরে নিজের ভাষায় উত্তর দিন।',

  // Advisor
  'AI advisor – AgroTrends': 'এআই পরামর্শক – অ্যাগ্রোট্রেন্ডস',
  'Ask the advisor': 'পরামর্শককে জিজ্ঞেস করুন',
  'Answers are written from stories farmers and agronomists published here, with links so you can check where the advice came from. A daily limit applies.':
    'উত্তর লেখা হয় এখানে কৃষক ও কৃষিবিদদের প্রকাশিত লেখা থেকে, লিংকসহ — যাতে আপনি দেখে নিতে পারেন পরামর্শ কোথা থেকে এসেছে। দিনে নির্দিষ্টসংখ্যক প্রশ্ন করা যায়।',
  'Your earlier questions': 'আপনার আগের প্রশ্ন',
  'Ask another question': 'আরেকটি প্রশ্ন করুন',
  Ask: 'জিজ্ঞেস করুন',
  'Sign in to ask': 'জিজ্ঞেস করতে সাইন ইন করুন',
  'No story on AgroTrends matched, so this answer is general advice.': 'অ্যাগ্রোট্রেন্ডসের কোনো লেখার সঙ্গে মেলেনি, তাই এটি সাধারণ পরামর্শ।',
  'This conversation': 'এই কথোপকথন',
  'Bangla or English: what you grow, where, and what you are seeing': 'বাংলা বা ইংরেজিতে: কী চাষ করছেন, কোথায়, আর কী দেখছেন',
  'For this {season} season': 'এই {season} মৌসুমের জন্য',
  'From these stories': 'এই লেখাগুলো থেকে',
  Sources: 'সূত্র',
  'Show older questions': 'আগের প্রশ্ন দেখুন',
  'Your questions to the advisor – AgroTrends': 'পরামর্শককে আপনার প্রশ্ন – অ্যাগ্রোট্রেন্ডস',
  'No questions yet. What you ask the advisor is kept here.': 'এখনো কোনো প্রশ্ন নেই। পরামর্শককে যা জিজ্ঞেস করবেন, এখানে থাকবে।',
  'Loading your questions': 'আপনার প্রশ্ন লোড হচ্ছে',

  // Accounts
  'Forgot your password?': 'পাসওয়ার্ড ভুলে গেছেন?',
  'Create an account': 'অ্যাকাউন্ট খুলুন',
  'Welcome back. Sign in to write, clap, follow and ask the advisor.': 'আবার স্বাগতম। লিখতে, হাততালি দিতে, অনুসরণ করতে আর পরামর্শককে জিজ্ঞেস করতে সাইন ইন করুন।',
  'E-mail': 'ই-মেইল',
  'Enter your e-mail address.': 'আপনার ই-মেইল ঠিকানা দিন।',
  'Enter your password.': 'আপনার পাসওয়ার্ড দিন।',
  Password: 'পাসওয়ার্ড',
  'Create account': 'অ্যাকাউন্ট খুলুন',
  'Create your account': 'আপনার অ্যাকাউন্ট খুলুন',
  'Join farmers, agronomists and students sharing what works in the field.': 'মাঠে যা কাজ করে তা ভাগ করে নেওয়া কৃষক, কৃষিবিদ ও শিক্ষার্থীদের সঙ্গে যোগ দিন।',
  'I want to join as': 'আমি যোগ দিতে চাই',
  Reader: 'পাঠক',
  Author: 'লেখক',
  'Read stories, ask and answer questions.': 'লেখা পড়ুন, প্রশ্ন করুন ও উত্তর দিন।',
  'Also publish stories, with your professional details shown.': 'আপনার পেশাগত তথ্যসহ লেখাও প্রকাশ করুন।',
  'Professional details': 'পেশাগত তথ্য',
  'Full name': 'পুরো নাম',
  Code: 'কোড',
  'Mobile number': 'মোবাইল নম্বর',
  Designation: 'পদবি',
  'Agronomist, Upazila Agriculture Officer': 'কৃষিবিদ, উপজেলা কৃষি কর্মকর্তা',
  'Separate with commas, for example: rice, soil health.': 'কমা দিয়ে আলাদা করুন, যেমন: ধান, মাটির স্বাস্থ্য।',
  'Occupation (optional)': 'পেশা (ঐচ্ছিক)',
  'Workplace or institution (optional)': 'কর্মস্থল বা প্রতিষ্ঠান (ঐচ্ছিক)',
  'Back to sign in': 'সাইন ইনে ফিরে যান',
  'Send reset link': 'রিসেট লিংক পাঠান',
  'Check your e-mail': 'ই-মেইল দেখুন',
  "If an account uses that address, we've sent it a link to set a new password.": 'এই ঠিকানায় কোনো অ্যাকাউন্ট থাকলে নতুন পাসওয়ার্ড দেওয়ার লিংক পাঠানো হয়েছে।',
  "Enter the e-mail you signed up with and we'll send you a link to set a new one.": 'যে ই-মেইল দিয়ে অ্যাকাউন্ট খুলেছিলেন সেটি দিন, নতুন পাসওয়ার্ডের লিংক পাঠিয়ে দেব।',
  'Send a new reset link': 'নতুন রিসেট লিংক পাঠান',
  'Set new password': 'নতুন পাসওয়ার্ড দিন',
  "This link isn't complete": 'লিংকটি সম্পূর্ণ নয়',
  'Open the link from the e-mail again, or ask for a new one.': 'ই-মেইলের লিংকটি আবার খুলুন, অথবা নতুন একটি চান।',
  'Set a new password': 'নতুন পাসওয়ার্ড দিন',
  "Choose a password you don't use anywhere else.": 'এমন পাসওয়ার্ড দিন যা আর কোথাও ব্যবহার করেন না।',
  'New password': 'নতুন পাসওয়ার্ড',
  'Repeat new password': 'নতুন পাসওয়ার্ড আবার দিন',

  // Library
  'Find stories': 'লেখা খুঁজুন',
  Authors: 'লেখক',
  'Show more authors': 'আরও লেখক দেখুন',
  'Browse topics': 'বিষয় দেখুন',
  'Library – AgroTrends': 'লাইব্রেরি – অ্যাগ্রোট্রেন্ডস',
  'Your library': 'আপনার লাইব্রেরি',
  'Reading list': 'পড়ার তালিকা',
  'Nothing saved yet': 'এখনো কিছু সংরক্ষণ করেননি',
  'Tap the bookmark on any story to keep it here for later.': 'পরে পড়ার জন্য যেকোনো লেখার বুকমার্ক চাপুন।',
  "You don't follow any authors yet. Follow one from their page or a story.": 'আপনি এখনো কোনো লেখককে অনুসরণ করছেন না। তাঁর পাতা বা লেখা থেকে অনুসরণ করুন।',
  'Loading authors': 'লেখক লোড হচ্ছে',

  // Errors
  "Can't reach AgroTrends right now. Check your connection and try again.": 'এখন অ্যাগ্রোট্রেন্ডসে পৌঁছানো যাচ্ছে না। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।',
  'Something went wrong on our side. Please try again.': 'আমাদের দিকে একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।',
  'Page not found': 'পাতাটি পাওয়া যায়নি',
  'The link may be old, or the story may have been unpublished.': 'লিংকটি পুরোনো হতে পারে, অথবা লেখাটি সরিয়ে নেওয়া হয়েছে।',
  'Go to the home page': 'প্রথম পাতায় যান',
}
